{% set name = "sift" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/svent/sift/archive/v{{ version }}.tar.gz
  sha256: bbbd5c472c36b78896cd7ae673749d3943621a6d5523d47973ed2fc6800ae4c8

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - sift --help

about:
  home: https://github.com/svent/sift
  license: GPL-3.0-only
  license_file:
    - LICENSE
    - license-files/
  summary: Fast and powerful open source alternative to grep
  dev_url: https://github.com/svent/sift

extra:
  recipe-maintainers:
    - danielnachun
